# Generated by Django 5.0.3 on 2024-03-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='meal',
            new_name='meals',
        ),
        migrations.AlterField(
            model_name='meal',
            name='type',
            field=models.CharField(choices=[('drink', 'Ichimlik'), ('meal', 'Ovqat'), ('salat', 'Salat')], default='meal', max_length=255),
        ),
    ]
