# Generated by Django 5.0.3 on 2024-03-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_rename_meal_order_meals_alter_meal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='image',
            field=models.ImageField(default='', upload_to='meals/'),
            preserve_default=False,
        ),
    ]
